name: action-jira-linker
on: [pull_request_target]

jobs:
  action-jira-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Jira Linker
        continue-on-error: true
        uses: exogee-technology/action-jira-linker@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-user: ${{ secrets.JIRA_USER }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://juristatv2.atlassian.net/
          fail-on-error: false
